# Generated by Django 5.0.2 on 2024-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsetting',
            name='currency',
            field=models.CharField(default='USDT', max_length=100),
        ),
    ]
