# Generated by Django 5.0.2 on 2024-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pointsetting_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsetting',
            name='min_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
