# Generated by Django 5.0.2 on 2024-03-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_subject_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam_duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
