# Generated by Django 5.0.2 on 2024-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_question_points_remove_question_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exam_duration',
        ),
        migrations.AddField(
            model_name='questionpattern',
            name='exam_duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
