# Generated by Django 5.0.2 on 2024-03-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_subject_exam_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': '    Courses'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': ' Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionpattern',
            options={'verbose_name': 'Question Pattern', 'verbose_name_plural': '  Question Patterns'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': '   Subjects'},
        ),
        migrations.AlterField(
            model_name='questionpattern',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Points for each Question'),
        ),
    ]
