# Generated by Django 5.0.2 on 2024-03-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='questionpattern',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
