# Generated by Django 4.2.7 on 2024-03-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_course_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattempt',
            name='question',
        ),
        migrations.AddField(
            model_name='userattempt',
            name='question_pattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.questionpattern'),
            preserve_default=False,
        ),
    ]
