# Generated by Django 4.2.7 on 2024-03-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_userattempt_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattempt',
            old_name='question_pattern',
            new_name='question',
        ),
    ]
