# Generated by Django 4.2.7 on 2024-03-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_rename_question_pattern_userattempt_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
