# Generated by Django 5.0.2 on 2024-03-07 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_question_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question')),
                ('user_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.userattempt')),
            ],
        ),
    ]
