# Generated by Django 5.0.2 on 2024-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_userattempt_created_at_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpattern',
            name='is_sequenced',
            field=models.BooleanField(default=False),
        ),
    ]
