# Generated by Django 5.0.2 on 2024-03-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_questionpattern_total_questions_served'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
