# Generated by Django 5.0.2 on 2024-03-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_useranswer_selected_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpattern',
            old_name='is_sequenced',
            new_name='random_serve',
        ),
    ]
